baseURL = "https://muuo.codes"
title = "Muuo{codes}"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true


[params]
    # The name to display as main title in the home page
    mainpagetitle = "MUUO.Codes"
    introPhoto = "swe.jpg"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to the early 90s!" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "As a passionate software developer, this platform serves as a hub for sharing my knowledge, experiences, and insights in the world of programming. Join me as I explore various programming languages, frameworks, and technologies, providing tutorials, code snippets, and tips to help you on your coding journey. Discover valuable resources, stay updated with the latest industry trends, and dive into practical examples that showcase the power of software development. Together, let's unravel the complexities of coding and unlock the potential of innovative solutions."
   
   
    # The name to display in the copyright section in the footer
    copyrightname = "Evans Muuo"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://github.com/codelord-evans"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    facebook = "https://facebook.com"
    twitter = "https://twitter.com/Evans_drv"
    linkedin = "https://www.linkedin.com/in/evansmuuo/"
    github = "https://github.com/codelord-evans"
    gitlab = "COOMING SOON"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false 

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Evans Muuo"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://github.com/codelord-evans"

    # Text to go before copyright information
    prefix = "[Muuo codes Blog by Evans Muuo](https://github.com/codelord-evans)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "Muuo Codes"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20
    
     [[menu.main]]
    identifier = "Projects" # An unique identifier for the button
    name = "Projects"       # A display name for the button
    url = "/Projects/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar


[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
